name: Auto Increment Version

on:
  push:
    paths:
      - 'firmware.bin'

jobs:
  update-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do codigo
        uses: actions/checkout@v3

      - name: Incrementar a Versao
        run: |
          if[ ! -f "firmware.bin" ]; then
            exit 0
          fi
          
          CURRENT_VERSION=$(cat version_id.txt 2>/dev/null || echo "1.00")
          NEW_VERSION=$(echo $CURRENT_VERSION | awk '{printf "%.2f", $1 + 0.01}')
          
          echo $NEW_VERSION > version_id.txt

      - name: Guardar as alterações (Commit e Push)
        run: |
          # Só avança se o ficheiro txt tiver sofrido realmente uma alteração
          if git diff --name-only | grep "version_id.txt"; then
            git config --global user.name "GitHub Actions Bot"
            git config --global user.email "actions@github.com"
            git add version_id.txt
            git commit -m "Autoupdate: Versão incrementada para $(cat version_id.txt)"
            git push
          else
            echo "Nada a gravar."
          fi
